secrets:
  db-passwd:
    file: .secrets/db-passwd
networks:
  default:
    name: stage-net
    external: true

services:
  app:
    build: .
    image: bpt-server:alpha
    container_name: bpt-stage
    networks:
      default:
        aliases:
          - app-stage
    secrets:
      - db-passwd
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
  db:
    image: postgres
    container_name: db-stage
    restart: always
    volumes:
      - /bpt/staging/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-passwd
      POSTGRES_DB: bpt
    secrets:
      - db-passwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
